// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Broadcast(arg1, arg2, arg3) {
  return window['go']['main']['App']['Broadcast'](arg1, arg2, arg3);
}

export function BroadcastToPeersOnly(arg1) {
  return window['go']['main']['App']['BroadcastToPeersOnly'](arg1);
}

export function HandleConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandleConnection'](arg1, arg2, arg3);
}

export function JoinRoom(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['JoinRoom'](arg1, arg2, arg3, arg4);
}

export function KillGhost(arg1) {
  return window['go']['main']['App']['KillGhost'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function StartHost(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartHost'](arg1, arg2, arg3, arg4);
}
