// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {net} from '../models';

export function Broadcast(arg1:string,arg2:string,arg3:net.Conn):Promise<void>;

export function BroadcastToPeersOnly(arg1:string):Promise<void>;

export function HandleConnection(arg1:net.Conn,arg2:string,arg3:boolean):Promise<void>;

export function JoinRoom(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function KillGhost(arg1:boolean):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StartHost(arg1:string,arg2:string,arg3:number,arg4:string):Promise<string>;
